/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "errorMessage": {
        "common": {
            "COM_COM001_001": string;
            "COM_COM001_002": string;
            "COM_COM001_003": string;
        };
        "auth": {
            "COM_CER001_001": string;
            "COM_CER001_002": string;
            "COM_CER001_003": string;
            "COM_CER002_001": string;
        };
        "user": {
            "MST_USR003_001": string;
            "MST_USR002_001": string;
            "MST_USR002_002": string;
            "MST_USR002_003": string;
            "MST_USR002_004": string;
            "MST_USR002_005": string;
            "MST_USR002_006": string;
            "MST_USR002_007": string;
            "MST_USR002_008": string;
        };
        "transportCompany": {
            "MST_TCM002_001": string;
            "MST_TCM002_002": string;
            "MST_TCM002_003": string;
            "MST_TCM002_004": string;
        };
        "driver": {
            "MST_DRV002_001": string;
            "MST_DRV002_002": string;
            "MST_DRV002_003": string;
        };
        "car": {
            "MST_CAR002_001": string;
            "MST_CAR002_002": string;
            "MST_CAR002_003": string;
        };
        "if": {
            "IF_MST001_001": string;
            "IF_REQ001_001": string;
            "IF_REQ001_002": string;
            "IF_REQ001_003": string;
            "IF_REQ001_004": string;
            "IF_ESI001_001": string;
            "IS_NOT_EMPTY": string;
            "IS_STRING": string;
            "MAX_LENGTH": string;
            "IS_IN": string;
            "IS_NUMBER": string;
            "IS_ENUM": string;
            "IS_YYYYMMDD": string;
            "IS_DYNAMIC_DECIMAL": string;
            "INVALID_HEADER": string;
            "RECORD_LIMIT": string;
            "MOVE_ERROR": string;
            "DOWNLOAD_ERROR": string;
        };
        "course": {
            "TRN_CRS002_001": string;
            "TRN_CRS004_001": string;
            "TRN_CRS005_001": string;
            "TRN_CRS010_001": string;
            "TRN_CRS013_001": string;
            "TRN_CRS014_001": string;
            "TRN_CRS015_001": string;
            "TRN_CRS016_001": string;
            "TRN_DLV003_001": string;
            "TRN_DLV003_002": string;
            "TRN_CRS011_005": string;
        };
        "highwayFee": {
            "TRN_CRS009_001": string;
            "TRN_CRS009_002": string;
            "TRN_CRS009_003": string;
            "TRN_CRS011_001": string;
            "TRN_CRS011_002": string;
        };
        "base": {
            "TRN_REQ005_001": string;
        };
        "spot": {
            "TRN_REQ006_001": string;
            "TRN_CRS006_001": string;
            "TRN_CRS007_001": string;
            "TRN_CRS007_002": string;
        };
        "slip": {
            "TRN_CRS011_003": string;
            "TRN_CRS011_004": string;
            "TRN_REQ007_001": string;
            "TRN_REQ002_001": string;
        };
        "gpsAct": {
            "TRN_CRS018_001": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
