version: '3.8'
services:
  mysql:
    image: mysql:8
    restart: always
    env_file:
      - .env.docker
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
  # redis:
  #   image: redis:7-alpine
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/data
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 3001:3000
    env_file:
      - .env.docker
    depends_on:
      - mysql
  batch:
    build:
      context: .
      dockerfile: ./apps/batch/Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - mysql
volumes:
  mysql:
  # redis:
