export const carriageCompanyGetAllUsers = [
  {
    driverId: 2,
    mUserId: 10,
    userId: 'carriage-employee4',
    userNm: 'carriage-employee4',
    userNmKn: 'carriage-employee4',
    mailAddress: 'carriage-employee4@gmail.com',
    roleDiv: '04',
    roleDivNm: '傭車権限',
    mainBaseId: 2,
    mainBaseNm: 'base name 2',
    transportCompanyId: 2,
    transportCompanyNm: 'Mock transport company 2',
  },
  {
    driverId: 1,
    mUserId: 9,
    userId: 'carriage-employee3',
    userNm: 'carriage-employee3',
    userNmKn: 'carriage-employee3',
    mailAddress: 'carriage-employee3@gmail.com',
    roleDiv: '04',
    roleDivNm: '傭車権限',
    mainBaseId: 2,
    mainBaseNm: 'base name 2',
    transportCompanyId: 2,
    transportCompanyNm: 'Mock transport company 2',
  },
  {
    driverId: null,
    mUserId: 6,
    userId: 'transport-employee3',
    userNm: 'transport-employee3',
    userNmKn: 'transport-employee3',
    mailAddress: 'transport-employee3@gmail.com',
    roleDiv: '03',
    roleDivNm: '運送会社権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: 2,
    transportCompanyNm: 'Mock transport company 2',
  },
];
