export const kyoSpacerGetAllUsers = [
  {
    driverId: null,
    mUserId: 6,
    userId: 'transport-employee3',
    userNm: 'transport-employee3',
    userNmKn: 'transport-employee3',
    mailAddress: 'transport-employee3@gmail.com',
    roleDiv: '03',
    roleDivNm: '運送会社権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: 2,
    transportCompanyNm: 'Mock transport company 2',
  },
  {
    driverId: null,
    mUserId: 5,
    userId: 'transport-employee2',
    userNm: 'transport-employee2',
    userNmKn: 'transport-employee2',
    mailAddress: 'transport-employee2@gmail.com',
    roleDiv: '03',
    roleDivNm: '運送会社権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
  {
    driverId: null,
    mUserId: 4,
    userId: 'transport-employee1',
    userNm: 'transport-employee1',
    userNmKn: 'transport-employee1',
    mailAddress: 'transport-employee1@gmail.com',
    roleDiv: '03',
    roleDivNm: '運送会社権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
  {
    driverId: null,
    mUserId: 3,
    userId: 'kyo-spacer2',
    userNm: 'kyo-spacer2',
    userNmKn: 'kyo-spacer2',
    mailAddress: 'kyo-spacer2@gmail.com',
    roleDiv: '02',
    roleDivNm: '京都スペーサー権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: null,
    transportCompanyNm: null,
  },
  {
    driverId: null,
    mUserId: 2,
    userId: 'kyo-spacer1',
    userNm: 'kyo-spacer1',
    userNmKn: 'kyo-spacer1',
    mailAddress: 'kyo-spacer1@gmail.com',
    roleDiv: '02',
    roleDivNm: '京都スペーサー権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: null,
    transportCompanyNm: null,
  },
];
