export const pagination = [
  {
    driverId: null,
    mUserId: 7,
    userId: 'carriage-employee1',
    userNm: 'carriage-employee1',
    userNmKn: 'carriage-employee1',
    mailAddress: 'carriage-employee1@gmail.com',
    roleDiv: '04',
    roleDivNm: '傭車権限',
    mainBaseId: 1,
    mainBaseNm: 'base name 1',
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
  {
    driverId: null,
    mUserId: 6,
    userId: 'transport-employee3',
    userNm: 'transport-employee3',
    userNmKn: 'transport-employee3',
    mailAddress: 'transport-employee3@gmail.com',
    roleDiv: '03',
    roleDivNm: '運送会社権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: 2,
    transportCompanyNm: 'Mock transport company 2',
  },
  {
    driverId: null,
    mUserId: 5,
    userId: 'transport-employee2',
    userNm: 'transport-employee2',
    userNmKn: 'transport-employee2',
    mailAddress: 'transport-employee2@gmail.com',
    roleDiv: '03',
    roleDivNm: '運送会社権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
];
