export const systemAdminSearchRoleDiv02 = [
  {
    driverId: null,
    mUserId: 3,
    userId: 'kyo-spacer2',
    userNm: 'kyo-spacer2',
    userNmKn: 'kyo-spacer2',
    mailAddress: 'kyo-spacer2@gmail.com',
    roleDiv: '02',
    roleDivNm: '京都スペーサー権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: null,
    transportCompanyNm: null,
  },
  {
    driverId: null,
    mUserId: 2,
    userId: 'kyo-spacer1',
    userNm: 'kyo-spacer1',
    userNmKn: 'kyo-spacer1',
    mailAddress: 'kyo-spacer1@gmail.com',
    roleDiv: '02',
    roleDivNm: '京都スペーサー権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: null,
    transportCompanyNm: null,
  },
];
