export const systemAdminSearchRoleDiv04 = [
  {
    driverId: 2,
    mUserId: 10,
    userId: 'carriage-employee4',
    userNm: 'carriage-employee4',
    userNmKn: 'carriage-employee4',
    mailAddress: 'carriage-employee4@gmail.com',
    roleDiv: '04',
    roleDivNm: '傭車権限',
    mainBaseId: 2,
    mainBaseNm: 'base name 2',
    transportCompanyId: 2,
    transportCompanyNm: 'Mock transport company 2',
  },
  {
    driverId: 1,
    mUserId: 9,
    userId: 'carriage-employee3',
    userNm: 'carriage-employee3',
    userNmKn: 'carriage-employee3',
    mailAddress: 'carriage-employee3@gmail.com',
    roleDiv: '04',
    roleDivNm: '傭車権限',
    mainBaseId: 2,
    mainBaseNm: 'base name 2',
    transportCompanyId: 2,
    transportCompanyNm: 'Mock transport company 2',
  },
  {
    driverId: null,
    mUserId: 8,
    userId: 'carriage-employee2',
    userNm: 'carriage-employee2',
    userNmKn: 'carriage-employee2',
    mailAddress: 'carriage-employee2@gmail.com',
    roleDiv: '04',
    roleDivNm: '傭車権限',
    mainBaseId: 1,
    mainBaseNm: 'base name 1',
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
  {
    driverId: null,
    mUserId: 7,
    userId: 'carriage-employee1',
    userNm: 'carriage-employee1',
    userNmKn: 'carriage-employee1',
    mailAddress: 'carriage-employee1@gmail.com',
    roleDiv: '04',
    roleDivNm: '傭車権限',
    mainBaseId: 1,
    mainBaseNm: 'base name 1',
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
];
