export const transportCompanyGetAllUsers = [
  {
    driverId: null,
    mUserId: 8,
    userId: 'carriage-employee2',
    userNm: 'carriage-employee2',
    userNmKn: 'carriage-employee2',
    mailAddress: 'carriage-employee2@gmail.com',
    roleDiv: '04',
    roleDivNm: '傭車権限',
    mainBaseId: 1,
    mainBaseNm: 'base name 1',
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
  {
    driverId: null,
    mUserId: 7,
    userId: 'carriage-employee1',
    userNm: 'carriage-employee1',
    userNmKn: 'carriage-employee1',
    mailAddress: 'carriage-employee1@gmail.com',
    roleDiv: '04',
    roleDivNm: '傭車権限',
    mainBaseId: 1,
    mainBaseNm: 'base name 1',
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
  {
    driverId: null,
    mUserId: 5,
    userId: 'transport-employee2',
    userNm: 'transport-employee2',
    userNmKn: 'transport-employee2',
    mailAddress: 'transport-employee2@gmail.com',
    roleDiv: '03',
    roleDivNm: '運送会社権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
  {
    driverId: null,
    mUserId: 4,
    userId: 'transport-employee1',
    userNm: 'transport-employee1',
    userNmKn: 'transport-employee1',
    mailAddress: 'transport-employee1@gmail.com',
    roleDiv: '03',
    roleDivNm: '運送会社権限',
    mainBaseId: null,
    mainBaseNm: null,
    transportCompanyId: 1,
    transportCompanyNm: 'Mock transport company 1',
  },
];
